### ISSUE TITLE
"get_all_area_category()" not working

### ISSUE THREAD

**Issue by banianzr** [prescriptive-analytics/starter-kit#1]
According to the [document](https://hzw77-demo.readthedocs.io/en/latest/api.html), `get_all_area_category()` should return a dictionary with all area id as the keys, and the category of the area as the value, however, when call this function, it returned "Segmentation fault: 11". Please check and fix it. Thank you!

**Comment by wingsweihua** [comment]
@gjzheng93 please try to fix this

**Comment by wingsweihua** [comment]
> According to the [document](https://hzw77-demo.readthedocs.io/en/latest/api.html), `get_all_area_category()` should return a dictionary with all area id as the keys, and the category of the area as the value, however, when call this function, it returned "Segmentation fault: 11". Please check and fix it. Thank you!

Can you tell me how you call this API?

All the data acess/ intervention APIs should be called after next_step(), as stated here: https://hzw77-demo.readthedocs.io/en/round2/api.html#simulation-config-api

**Comment by banianzr** [comment]
The issue is existing in round1. It seems that the API works fine after update ...
