### ISSUE TITLE
ImportError: libboost_filesystem.so.1.69.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by weicao1990** [prescriptive-analytics/starter-kit#3]
The new simulator raise error during import, for both direct install and docker install.

**Comment by wingsweihua** [comment]
@gjzheng93 Please take a look into this.

**Comment by gjzheng93** [comment]
> The new simulator raise error during import, for both direct install and docker install.

are you using windows? @weicao1990

**Comment by weicao1990** [comment]
@gjzheng93 
I am using ubuntu 18.04. I fixed this issue after installing latest boost and remove the older version.
