### ISSUE TITLE
evaluation in round 2

### ISSUE THREAD

**Issue by weicao1990** [prescriptive-analytics/starter-kit#4]
Hi,
Has the evaluation in round 2 changed? From the document, it seems evaluation metric stays unchanged. However the submission result is quite strange. 

I calculate the score based on cnt.txt file. My submission should be about 3.0, but the leadboard returns above 10000. 

Moreover, the scenario1 is the same as the previous round where I received 2.x score. But when I submit the same algorithm, current lead board still returns a huge penalty score.

**Comment by weicao1990** [comment]
@wingsweihua @gjzheng93 
I know the reason. 
I checked the document history, in commit 3ad560d, the parameters are set as \theta_I = 500, \theta_Q=10000; but it was reset back to \theta_I = 1000 and \theta_Q=100000 in the current document.

The leaderboard uses (500, 10000) parameter setting. So you may need to update your document.

**Comment by wingsweihua** [comment]
Thanks for the notification. We've updated the doc.

**Comment by weicao1990** [comment]
@wingsweihua \theta_Q should be 10,000, not 100,000
