### ISSUE TITLE
Import Error: libboost_filesystem.so.1.69.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by banianzr** [prescriptive-analytics/starter-kit#5]
The simulator works fine on my Mac Book Pro. Howerver, when I ran example.py under Ubuntu 18.04, this error popped. And I cannot update boost library to this version (since the latest version for Ubuntu is 1.65.1.0). In Round 1, this error was not seen. 
Could you please check the library and give some suggestions? Thank you very much!

**Comment by weicao1990** [comment]
@banianzr I also face this issue. My solution is to install the latest boost from source code.

**Comment by banianzr** [comment]
@weicao1990 I've installed the latest boost. But the official document recommend 1.58 ...

**Comment by wingsweihua** [comment]
Sorry we've reversed back to 1.58 now. Could you guys try it on 1.58?
