### ISSUE TITLE
I ran python3 submit.py to simulate 15 rounds, in 12 rounds it has 11 areas and in 3 rounds it has 98 areas. Why is that?

### ISSUE THREAD

**Issue by tranvanluan2** [prescriptive-analytics/starter-kit#6]

**Comment by banianzr** [comment]
Please refer to the [Document for Simulator](https://hzw77-demo.readthedocs.io/en/round2/index.html)
In Round 2, there're 5 scenarios, and in one of these scenarios there're 98 areas ...
